sudo: false

language: go
go:
  - "1.13"
  - "1.x"
env:
  - GO111MODULE=on PATH=$HOME/protoc/bin:$PATH COVERALLS_TOKEN=z1YLEbP3sMJbfShkAL0JlDs0G02tLjKm8

before_install:
  - go get -u golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-pro

cache:
  directories:
    - $GOPATH/pkg/mod

notifications:
  email: false